#!/usr/bin/env bash

docker run --rm -v ${PWD}:${PWD} -w ${PWD} -u 1000 nbrun/svn-client:latest svn co https://plugins.svn.wordpress.org/spiff-3d-product-customizer svn-repo
cd svn-repo
cp ../spiff-connect/* trunk/
docker run --rm -v ${PWD}:${PWD} -w ${PWD} -u 1000 nbrun/svn-client:latest svn add trunk/*
cp ../assets/* assets/
docker run --rm -v ${PWD}:${PWD} -w ${PWD} -u 1000 nbrun/svn-client:latest svn add assets/*
docker run --rm -v ${PWD}:${PWD} -w ${PWD} -u 1000 nbrun/svn-client:latest svn --username ${SVN_CREDS_USR} --password ${SVN_CREDS_PSW} ci -m "Version ${VERSION}"
docker run --rm -v ${PWD}:${PWD} -w ${PWD} -u 1000 nbrun/svn-client:latest svn cp trunk tags/${VERSION}
docker run --rm -v ${PWD}:${PWD} -w ${PWD} -u 1000 nbrun/svn-client:latest svn --username ${SVN_CREDS_USR} --password ${SVN_CREDS_PSW} ci -m "Tag Version ${VERSION}"
