version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8888:80
    environment:
      SPIFF_API_BASE: 'http://host.docker.internal:8080'
      SPIFF_API_US_BASE: 'http://host.docker.internal:8080'
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html
      - ./spiff-connect:/var/www/html/wp-content/plugins/spiff-connect

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

  adminer:
      image: adminer
      restart: always
      ports:
        - 8889:8080

volumes:
  wordpress:
  db:
